### ISSUE TITLE
_read_database_callback not called

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNakerExternalDevicesPlugin#41]
Creating a SpynnakerLiveSpikesConnection object and passing local_port as a parameter results in _read_database_callback not being called ever.

This then breaks reception/transmission as the object has no knowledge of IP:port or receive_packet_callbacks.

**Comment by andrewgait** [comment]
This may be referring to something which existed in version 3.0.0, but I can't see it - _read_database_callback has always been called when a SpynnakerLiveSpikesConnection is created - has it already been fixed?  If not is there an example script?

**Comment by rowleya** [comment]
This would happen if the SpynnakerLiveSpikesConnection is created with a different port and the tools are not told about it.  You would have to tell the tools that the connection exists, or else it won't tell you it has created the database.  This can be done (in the current git version) by calling:
```
p.extra_models.register_database_notification_request(hostname, port, None)
```

where ```hostname``` is the host on which you have created the SpiNNakerLiveSpikesConnection (localhost if the same as the tools are running on) and ```port``` is the port of the connection.

I will close this issue, as I think the above solves it, but reopen if not.
