### ISSUE TITLE
munich_io_protocol.py did not compile without a hack

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNakerExternalDevicesPlugin#45]
spynnaker_external_devices_plugin/pyNN/external_devices_models/munich_io_protocol.py

Did not compile without adding a hack

     def bias_values(self, bias_id, bias_value):
       # CYB ADDED "JUNK" to get file past sphink
         return MultiCastCommand(
             key="JUNK",
             payload="JUNK",
             time=0, repeat=1, delay_between_repeats=100)

**Comment by alan-stokes** [comment]
my fault, forgot to deal with it during the first run through. Id guess the payload should = bias_value, but the key will be some calculation based off the munich protocol doc. The bias value command isn't a criticle command to be honest, motors, retina, laser, compass, speaker seemed more important (excuse not reason).

**Comment by alan-stokes** [comment]
looks like master has had them changed. so sorted. closing issue.
