### ISSUE TITLE
munch motor device bust

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNakerExternalDevicesPlugin#56]
needs fixing (came up in capo)

**Comment by alan-stokes** [comment]
only issue on spalloc machines......which is kinda expected, but could be done given a spalloc of 1 board isnt a wrap around and therefore should have a spinnaker link available. esp if that spalloced machine was setup thus

**Comment by rowleya** [comment]
Does this currently fail?  We were running the pushbot on a spalloc board in capo...

**Comment by alan-stokes** [comment]
seems so. the max machine generaotr on a 24 board wrap puts wrap arounds by default

**Comment by alan-stokes** [comment]
wrap arounds = failure for putting spinnaker link ids in. fixing by setting spalloc max amchine generaotr to demand no wrap arounds. given that one really doesnt care.

**Comment by alan-stokes** [comment]
the gotcha is that in capo, we only had 1 board, this issue occurs when spalloc has many boards in its machine

**Comment by alan-stokes** [comment]
if we have multiple, we either have to bastardise the max x and y to meet the virutal machine requirements of 
"It is invalid to set version, width, height, with_wrap_arounds to None, 48, 24, False: A generic machine without wrap arounds must be either have a width and height which are both either 2 or 8 or a width - 4 and height - 4 that are divisible by 12"

or we need to ensure it disconnects a link for the spinnaker links in these cases. 

my personal preference is to have the virtual machine to have a add_spinnaker_link param which if set, does not put the link from etherent connected chips down south west and thus allow spinnaker links to work correctly.

**Comment by alan-stokes** [comment]
or we could jsut leave it, as in this state, 1 48 chip board spalloced will work. and locals work.... so its a edge case we're dealing with here.

**Comment by rowleya** [comment]
The issue is that if you put an external device in a spalloc machine, spalloc won't know and will therefore probably enable the FPGA and cause havoc (and possibly blow up boards).  Thus I think this is correct.  You can have 1 board in a spalloc setup with a device attached, but that is it.

**Comment by rowleya** [comment]
If it works with a single board, I say that is enough, and so this can then be closed

**Comment by alan-stokes** [comment]
closed until there is a better process defined for dealing with external devices in multiboard spalloc systems. As it should be possible, but unlikely to be a easy quick fix

**Comment by rowleya** [comment]
It would require spalloc to know which boards a device is connected to so it doesn't go and turn on that FPGA.  We would then have to also know this in the max machine generator, so we also manually remove that link.
